/**
 * ╔══════════════════════════════════════════════════════╗
 * ║  RENDER ENGINE                                       ║
 * ║  File: js/render.js                                  ║
 * ║                                                      ║
 * ║  Reads RESUME from data.js and builds DOM elements.  ║
 * ║  Do NOT edit this file unless changing layout logic. ║
 * ╚══════════════════════════════════════════════════════╝
 */

/* ── Helpers ── */
const el  = (id)      => document.getElementById(id);
const qs  = (sel, ctx) => (ctx || document).querySelector(sel);
const qsa = (sel, ctx) => [...(ctx || document).querySelectorAll(sel)];

function tag(type, cls, html) {
  const e = document.createElement(type);
  if (cls)  e.className   = cls;
  if (html) e.innerHTML   = html;
  return e;
}

function chipHTML(arr, chipClass = 'chip chip-accent') {
  return arr.map(t => `<span class="${chipClass}">${t}</span>`).join('');
}

function bulletHTML(arr) {
  return '<ul class="exp-bullets">' + arr.map(b => `<li>${b}</li>`).join('') + '</ul>';
}

/* ══════════════════════════════════════════
   INDEX PAGE
══════════════════════════════════════════ */
function renderIndex() {
  if (!el('hero-name')) return;
  const R = RESUME;

  // Name
  el('hero-name').innerHTML = `${R.name.first}<br><span class="accent">${R.name.last.split(' ')[0]}</span><br>${R.name.last.split(' ').slice(1).join(' ')}`;

  // Tagline
  if (el('hero-tagline')) el('hero-tagline').textContent = R.tagline;

  /*// Availability badge
  if (el('avail-badge')) {
    el('avail-badge').innerHTML = `<span class="avail-dot"></span> ${R.availability.label} — ${R.availability.location}`;
    el('avail-badge').style.display = R.availability.open ? 'inline-flex' : 'none';
  }*/

  // Stats
  const statsEl = el('hero-stats');
  if (statsEl) {
    statsEl.innerHTML = R.stats.map(s => `
      <div>
        <div class="stat-num">${s.num}${s.sup ? `<sup>${s.sup}</sup>` : ''}</div>
        <div class="stat-label">${s.label}</div>
      </div>`).join('');
  }

  // Hero panel skills
  const panelEl = el('hero-panel-skills');
  if (panelEl) {
    panelEl.innerHTML = R.heroPanelSkills.map(s => `
      <div class="skill-row">
        <div>
          <div class="skill-row-name">${s.name}</div>
          <div class="skill-row-sub">${s.sub}</div>
        </div>
        <div class="skill-bar-bg">
          <div class="skill-bar-fill" data-width="${s.pct}" style="width:0"></div>
        </div>
      </div>`).join('');
  }

  // Tool chips in hero panel
  const toolChipsEl = el('hero-tool-chips');
  if (toolChipsEl) {
    toolChipsEl.innerHTML = R.tools.map(t => `<span class="tool-chip">${t.name}</span>`).join('');
  }
}

/* ══════════════════════════════════════════
   ABOUT PAGE
══════════════════════════════════════════ */
function renderAbout() {
  if (!el('about-contact-cards')) return;
  const R = RESUME;

  // Contact cards
  el('about-contact-cards').innerHTML = `
    <div class="about-card">
      <div class="ac-icon">🎓</div>
      <div class="ac-title">Current Studies</div>
      <div class="ac-body">${R.education[0].degree} — ${R.education[0].institution}, ${R.education[0].location.split(',')[0]} · ${R.education[0].period}</div>
    </div>
    <div class="about-card">
      <div class="ac-icon">📍</div>
      <div class="ac-title">Location</div>
      <div class="ac-body">${R.contact.location} · Open to roles across Greater Sydney</div>
    </div>
    <div class="about-card">
      <div class="ac-icon">📞</div>
      <div class="ac-title">Contact</div>
      <div class="ac-body">
        <a href="mailto:${R.contact.email}" style="color:var(--accent)">${R.contact.email}</a><br>
        ${R.contact.phone}
      </div>
    </div>
    <div class="about-card">
      <div class="ac-icon">🌐</div>
      <div class="ac-title">Languages Spoken</div>
      <div class="ac-body">Fluent in ${R.languages.length} languages:</div>
      <div class="lang-chips" style="display:flex;flex-wrap:wrap;gap:.35rem;margin-top:.5rem;">
        ${R.languages.map(l => `<span class="chip chip-accent">${l.lang}</span>`).join('')}
      </div>
    </div>`;

  // Education cards
  const eduEl = el('education-cards');
  if (eduEl) {
    eduEl.innerHTML = R.education.map(e => `
      <div class="edu-card reveal">
        <div class="edu-icon">${e.icon}</div>
        <div>
          <div class="edu-degree">${e.degree}</div>
          <div class="edu-uni">${e.institution}</div>
          <div class="edu-meta">${e.location} &nbsp;·&nbsp; ${e.period}</div>
          <div style="margin-top:.8rem;display:flex;gap:.5rem;flex-wrap:wrap;">
            <span class="chip chip-success">${e.status}</span>
            <span class="chip">${e.institution}</span>
          </div>
        </div>
      </div>`).join('');
  }

  // Name mentions in body text
  qsa('[data-name]').forEach(n => n.textContent = R.name.display);
}

/* ══════════════════════════════════════════
   EXPERIENCE PAGE
══════════════════════════════════════════ */
function renderExperience() {
  const expEl = el('experience-timeline');
  if (!expEl) return;
  const R = RESUME;

  expEl.innerHTML = R.experience.map((job, i) => `
    <div class="exp-card ${job.current ? 'new' : ''} reveal ${i > 0 ? 'reveal-delay-' + Math.min(i, 3) : ''}">
      <div class="exp-badges">
        ${job.current ? '<span class="chip chip-success">Current Role</span>' : ''}
        <span class="chip">${job.period.split('–')[0].trim()}</span>
        <span class="chip">${job.location}</span>
        ${job.duration ? `<span class="chip">${job.duration}</span>` : ''}
      </div>
      <div class="exp-header">
        <div>
          <div class="exp-role">${job.role}</div>
          <div class="exp-company">${job.company} · ${job.location}</div>
        </div>
        <div class="exp-meta">${job.period}</div>
      </div>
      ${bulletHTML(job.bullets)}
      <div style="margin-top:1.2rem;display:flex;gap:.4rem;flex-wrap:wrap;">
        ${chipHTML(job.tags)}
      </div>
    </div>`).join('');

  // Sidebar career summary
  const summaryEl = el('career-summary');
  if (summaryEl) {
    summaryEl.innerHTML = R.experience.map(job => `
      <div class="sidebar-item">
        <span class="sidebar-dot ${job.current ? 'success' : ''}"></span>
        ${job.role} · ${job.location.split(',')[0]}
      </div>`).join('');
  }

  // Extracurricular
  const extraEl = el('extracurricular-grid');
  if (extraEl) {
    extraEl.innerHTML = R.extracurricular.map((item, i) => `
      <div class="card card-accent-top reveal ${i > 0 ? 'reveal-delay-' + i : ''}">
        <div style="font-size:1.4rem;margin-bottom:.8rem;">${item.icon}</div>
        <div style="font-family:'Syne',sans-serif;font-size:.88rem;font-weight:700;color:var(--navy);margin-bottom:.5rem;">${item.title}</div>
        ${bulletHTML(item.bullets)}
        <div style="margin-top:.8rem;display:flex;gap:.35rem;flex-wrap:wrap;">
          ${chipHTML(item.tags)}
        </div>
      </div>`).join('');
  }
}

/* ══════════════════════════════════════════
   PROJECTS PAGE
══════════════════════════════════════════ */
function renderProjects() {
  const projEl = el('projects-grid');
  if (!projEl) return;
  const R = RESUME;

  const normalProjects = R.projects.filter(p => !p.featured);
  const featured = R.projects.find(p => p.featured);

  let html = '';

  // Featured wide card first
  if (featured) {
    html += `
      <div class="project-card-wide reveal" style="grid-column:span 2;">
        <div>
          <div class="proj-num">${featured.num} · Featured</div>
          <div class="proj-title">${featured.title}</div>
          <p class="proj-desc">${featured.desc}</p>
          ${bulletHTML(featured.bullets)}
          <div class="proj-tags" style="margin-top:1rem;">${chipHTML(featured.tags)}</div>
          ${featured.link ? `<a href="${featured.link}" target="_blank" rel="noopener" class="btn btn-ghost" style="margin-top:1.2rem;font-size:.68rem;">View on GitHub →</a>` : ''}
        </div>
        <div style="display:flex;flex-direction:column;justify-content:space-between;">
          <div class="proj-visual">${featured.icon}</div>
          <div class="proj-stats">
            <div><div class="proj-stat-num">ML</div><div class="proj-stat-label">Approach</div></div>
            <div><div class="proj-stat-num">Real-time</div><div class="proj-stat-label">Prediction</div></div>
            <div><div class="proj-stat-num">Flask</div><div class="proj-stat-label">Interface</div></div>
          </div>
        </div>
      </div>`;
  }

  // Normal cards
  normalProjects.forEach((p, i) => {
    html += `
      <div class="project-card-full reveal ${i > 0 ? 'reveal-delay-' + i : ''}">
        <div class="proj-num">${p.num}</div>
        <div class="proj-title">${p.title}</div>
        <p class="proj-desc">${p.desc}</p>
        ${bulletHTML(p.bullets)}
        <div class="proj-tags" style="margin-top:.8rem;">${chipHTML(p.tags)}</div>
        ${p.link ? `<a href="${p.link}" target="_blank" rel="noopener" class="btn btn-ghost" style="margin-top:1rem;font-size:.65rem;">GitHub →</a>` : ''}
      </div>`;
  });

  projEl.innerHTML = html;

  // CTF cards
  const ctfEl = el('ctf-grid');
  if (ctfEl) {
    const ctf = R.extracurricular.filter(e => e.title.includes('CTF') || e.title.includes('Research'));
    ctfEl.innerHTML = ctf.map((item, i) => `
      <div class="card card-accent-top reveal ${i > 0 ? 'reveal-delay-1' : ''}">
        <div style="font-size:1.6rem;margin-bottom:1rem;">${item.icon}</div>
        <div style="font-family:'Syne',sans-serif;font-size:.95rem;font-weight:700;color:var(--navy);margin-bottom:.7rem;">${item.title}</div>
        ${bulletHTML(item.bullets)}
        <div style="margin-top:1rem;display:flex;gap:.4rem;flex-wrap:wrap;">${chipHTML(item.tags)}</div>
      </div>`).join('');
  }
}

/* ══════════════════════════════════════════
   SKILLS PAGE
══════════════════════════════════════════ */
function renderSkills() {
  const R = RESUME;

  function skillCategoryHTML(title, items, dark = false) {
    const nameStyle = dark ? 'style="color:#a0b4d0;"' : '';
    const pctStyle  = dark ? 'style="color:#2a4070;"' : '';
    return `
      <div class="skill-category reveal">
        <div class="sc-heading">${title}</div>
        <div class="sc-items">
          ${items.map(s => `
            <div class="sc-item">
              <div class="sc-item-row">
                <span class="sc-item-name" ${nameStyle}>${s.name}</span>
                ${s.level
                  ? `<span class="sc-item-pct" ${pctStyle}>${s.level}</span>`
                  : `<span class="sc-item-pct" ${pctStyle}>${s.pct}%</span>`
                }
              </div>
              <div class="skill-bar-bg">
                <div class="skill-bar-fill" data-width="${s.pct}" style="width:0"></div>
              </div>
            </div>`).join('')}
        </div>
      </div>`;
  }

  // Core skills (light bg)
  const coreEl = el('skills-core');
  if (coreEl) {
    coreEl.innerHTML =
      skillCategoryHTML('🔐 Cybersecurity', R.skills.security) +
      skillCategoryHTML('🌐 Networking',    R.skills.networking) +
      skillCategoryHTML('💻 Programming',   R.skills.programming);
  }

  // Tools
  const toolsEl = el('tools-grid');
  if (toolsEl) {
    toolsEl.innerHTML = R.tools.map((t, i) => `
      <div class="tool-card reveal ${i % 2 === 1 ? 'reveal-delay-1' : ''}">
        <div class="tool-icon">${t.icon}</div>
        <div class="tool-name">${t.name}</div>
        <div class="tool-cat">${t.category}</div>
      </div>`).join('');
  }

  // Soft / Languages (dark bg)
  const softEl = el('skills-soft');
  if (softEl) {
    softEl.innerHTML =
      skillCategoryHTML('🤝 Professional', R.skills.professional, true) +
      skillCategoryHTML('🌐 Languages',    R.languages.map(l => ({ name: l.lang, pct: l.pct, level: l.level })), true) +
      skillCategoryHTML('📋 Frameworks',   R.skills.frameworks, true);
  }
}

/* ══════════════════════════════════════════
   CONTACT PAGE
══════════════════════════════════════════ */
function renderContact() {
  const R = RESUME;

  // Contact cards
  const cardsEl = el('contact-cards');
  if (cardsEl) {
    cardsEl.innerHTML = `
      <a class="contact-card" href="mailto:${R.contact.email}">
        <span class="cc-icon">✉️</span>
        <div><div class="cc-label">Email</div><div class="cc-value">${R.contact.email}</div><div class="cc-note">Best for internship inquiries</div></div>
      </a>
      <a class="contact-card" href="tel:${R.contact.phone.replace(/\s/g,'')}">
        <span class="cc-icon">📞</span>
        <div><div class="cc-label">Phone</div><div class="cc-value">${R.contact.phone}</div><div class="cc-note">Sydney, NSW — AEST</div></div>
      </a>
      <a class="contact-card" href="${R.contact.linkedinUrl}" target="_blank" rel="noopener">
        <span class="cc-icon">💼</span>
        <div><div class="cc-label">LinkedIn</div><div class="cc-value">${R.contact.linkedin}</div><div class="cc-note">Professional network</div></div>
      </a>
      <div class="contact-card" style="cursor:default;">
        <span class="cc-icon">📍</span>
        <div><div class="cc-label">Location</div><div class="cc-value">${R.contact.location}</div><div class="cc-note">${R.contact.locationNote}</div></div>
      </div>`;
  }
/*
  // Availability widget
  const availEl = el('avail-widget-rows');
  if (availEl) {
    const av = R.availability;
    availEl.innerHTML = `
      <div class="aw-row"><span class="aw-label">Internship</span><div class="aw-row-inner"><div class="aw-dot ${av.open ? 'green' : 'yellow'}"></div><span class="aw-value">${av.open ? 'Open' : 'Not Available'}</span></div></div>
      <div class="aw-row"><span class="aw-label">Start Date</span><span class="aw-value">${av.startDate}</span></div>
      <div class="aw-row"><span class="aw-label">Location</span><span class="aw-value">${av.location}</span></div>
      <div class="aw-row"><span class="aw-label">Work Type</span><span class="aw-value">${av.workType}</span></div>
      <div class="aw-row"><span class="aw-label">Focus Areas</span><span class="aw-value">${av.focusAreas}</span></div>`;
  }*/
}

/* ══════════════════════════════════════════
   SHARED — Footer & Nav data
══════════════════════════════════════════ */
function renderSharedData() {
  const R = RESUME;
  // Footer email/linkedin links
  qsa('[data-email]').forEach(a => { a.href = `mailto:${R.contact.email}`; a.textContent = a.dataset.emailLabel || 'Email'; });
  qsa('[data-linkedin]').forEach(a => { a.href = R.contact.linkedinUrl; });
  qsa('[data-github]').forEach(a => { a.href = R.contact.githubUrl; });
  // Copyright year
  qsa('.year').forEach(e => e.textContent = new Date().getFullYear());
  // Page <title> suffix
  const titleEl = document.querySelector('title');
  if (titleEl && !titleEl.dataset.custom) {
    titleEl.textContent = titleEl.textContent.replace('__NAME__', R.name.display);
  }
}

/* ── Run all renderers ── */
document.addEventListener('DOMContentLoaded', () => {
  renderSharedData();
  renderIndex();
  renderAbout();
  renderExperience();
  renderProjects();
  renderSkills();
  renderContact();
});
